// <auto-generated />
using System;
using House_of_law_api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace House_of_law_api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260202104325_AddErrorLogToImportJob")]
    partial class AddErrorLogToImportJob
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuditsFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Audit")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("audit");

                    b.Property<long?>("DeptCode")
                        .HasColumnType("bigint")
                        .HasColumnName("dept_code");

                    b.Property<long?>("FileCode")
                        .HasColumnType("bigint")
                        .HasColumnName("file_code");

                    b.Property<int?>("UserAdded")
                        .HasColumnType("int")
                        .HasColumnName("user_added");

                    b.Property<int?>("UserUpdated")
                        .HasColumnType("int")
                        .HasColumnName("user_updated");

                    b.HasKey("Id");

                    b.ToTable("audits_files");
                });

            modelBuilder.Entity("AutoNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AutoNumberValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("auto_number");

                    b.Property<string>("CaseRef")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("case_ref");

                    b.Property<string>("Claimant")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("claimant");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_added");

                    b.Property<int?>("DeptCode")
                        .HasColumnType("int")
                        .HasColumnName("dept_code");

                    b.Property<long?>("FileCode")
                        .HasColumnType("bigint")
                        .HasColumnName("file_code");

                    b.Property<int?>("ImportJobId")
                        .HasColumnType("int")
                        .HasColumnName("import_job_id");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<int?>("ParentAutoId")
                        .HasColumnType("int")
                        .HasColumnName("parent_auto_id");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.Property<int?>("UserAdded")
                        .HasColumnType("int")
                        .HasColumnName("user_added");

                    b.HasKey("Id");

                    b.HasIndex("ImportJobId");

                    b.ToTable("auto_numbers");
                });

            modelBuilder.Entity("CallcenterStatement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConnectedStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("connected_status");

                    b.Property<string>("ContactMethod")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contact_method");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_added");

                    b.Property<long?>("DeptCode")
                        .HasColumnType("bigint")
                        .HasColumnName("dept_code");

                    b.Property<long?>("FileCode")
                        .HasColumnType("bigint")
                        .HasColumnName("file_code");

                    b.Property<string>("NextAction")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("next_action");

                    b.Property<DateTime?>("NextDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("next_date");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone_number");

                    b.Property<string>("PhoneOwner")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone_owner");

                    b.Property<decimal?>("PromiseAmount")
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("promise_amount");

                    b.Property<int?>("UserAdded")
                        .HasColumnType("int")
                        .HasColumnName("user_added");

                    b.HasKey("Id");

                    b.ToTable("callcenter_statements");
                });

            modelBuilder.Entity("Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Code")
                        .HasColumnType("int")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("departments");
                });

            modelBuilder.Entity("EmployeeTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignedToId")
                        .HasColumnType("int")
                        .HasColumnName("assigned_to_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("department");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("due_date");

                    b.Property<string>("EmployeeComment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("employee_comment");

                    b.Property<string>("Priority")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("priority");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<string>("SupervisorComment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("supervisor_comment");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("CreatedById");

                    b.ToTable("employee_tasks");
                });

            modelBuilder.Entity("FileClassification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Classification")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("classification");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("code");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_added");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("department");

                    b.Property<long?>("DeptCode")
                        .HasColumnType("bigint")
                        .HasColumnName("dept_code");

                    b.Property<long?>("FileCode")
                        .HasColumnType("bigint")
                        .HasColumnName("file_code");

                    b.Property<int?>("UserAdded")
                        .HasColumnType("int")
                        .HasColumnName("user_added");

                    b.HasKey("Id");

                    b.ToTable("file_classifications");
                });

            modelBuilder.Entity("FileDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Client")
                        .HasColumnType("int")
                        .HasColumnName("client");

                    b.Property<string>("ContractNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contract_no");

                    b.Property<int?>("CourtUser")
                        .HasColumnType("int")
                        .HasColumnName("court_user");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_added");

                    b.Property<DateTime?>("DateFinished")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_finished");

                    b.Property<decimal?>("DeptAmount")
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("dept_amount");

                    b.Property<long?>("DeptCode")
                        .HasColumnType("bigint")
                        .HasColumnName("dept_code");

                    b.Property<long?>("FileCode")
                        .HasColumnType("bigint")
                        .HasColumnName("file_code");

                    b.Property<int?>("ImportJobId")
                        .HasColumnType("int")
                        .HasColumnName("import_job_id");

                    b.Property<int?>("LawyerUser")
                        .HasColumnType("int")
                        .HasColumnName("lawyer_user");

                    b.Property<int?>("LegalAdvisorUser")
                        .HasColumnType("int")
                        .HasColumnName("legal_advisor_user");

                    b.Property<string>("LegalPlaintiff")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("legal_plaintiff");

                    b.Property<int?>("MdUser")
                        .HasColumnType("int")
                        .HasColumnName("md_user");

                    b.Property<string>("PatchNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("patch_no");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reason");

                    b.HasKey("Id");

                    b.HasIndex("ImportJobId");

                    b.ToTable("file_details");
                });

            modelBuilder.Entity("FileStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_added");

                    b.Property<int?>("DeptCode")
                        .HasColumnType("int")
                        .HasColumnName("dept_code");

                    b.Property<long?>("FileCode")
                        .HasColumnType("bigint")
                        .HasColumnName("file_code");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("file_statuses");
                });

            modelBuilder.Entity("House_of_law_api.Modules.AdditionalAmount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AmountType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("amount_type");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_added");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_updated");

                    b.Property<long?>("DeptCode")
                        .HasColumnType("bigint")
                        .HasColumnName("dept_code");

                    b.Property<bool?>("Enabled")
                        .HasColumnType("bit")
                        .HasColumnName("enabled");

                    b.Property<long?>("FileCode")
                        .HasColumnType("bigint")
                        .HasColumnName("file_code");

                    b.Property<int?>("UserAdded")
                        .HasColumnType("int")
                        .HasColumnName("user_added");

                    b.Property<int?>("UserUpdated")
                        .HasColumnType("int")
                        .HasColumnName("user_updated");

                    b.Property<decimal?>("Value")
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.ToTable("additional_amounts");
                });

            modelBuilder.Entity("House_of_law_api.Modules.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("attach_code");

                    b.Property<string>("AttachType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("attach_type");

                    b.Property<string>("AutoNumberCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("auto_number_code");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_added");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_updated");

                    b.Property<long?>("DeptCode")
                        .HasColumnType("bigint")
                        .HasColumnName("dept_code");

                    b.Property<bool?>("Enabled")
                        .HasColumnType("bit")
                        .HasColumnName("enabled");

                    b.Property<long?>("FileCode")
                        .HasColumnType("bigint")
                        .HasColumnName("file_code");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<int?>("UserAdded")
                        .HasColumnType("int")
                        .HasColumnName("user_added");

                    b.Property<int?>("UserUpdated")
                        .HasColumnType("int")
                        .HasColumnName("user_updated");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.ToTable("attachments");
                });

            modelBuilder.Entity("ImportJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int")
                        .HasColumnName("created_by_id");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("int")
                        .HasColumnName("error_count");

                    b.Property<byte[]>("ErrorLogFile")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("error_log_file");

                    b.Property<string>("ErrorLogFileName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error_log_file_name");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error_message");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("file_name");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("job_type");

                    b.Property<int>("ProcessedRows")
                        .HasColumnType("int")
                        .HasColumnName("processed_rows");

                    b.Property<int>("Progress")
                        .HasColumnType("int")
                        .HasColumnName("progress");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<string>("StoredFileName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("stored_file_name");

                    b.Property<int>("TotalRows")
                        .HasColumnType("int")
                        .HasColumnName("total_rows");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("import_jobs");
                });

            modelBuilder.Entity("LoginHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("login_time");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("role");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_agent");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("LoginTime");

                    b.HasIndex("UserId");

                    b.ToTable("login_histories");
                });

            modelBuilder.Entity("Mail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("body");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_added");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_updated");

                    b.Property<long?>("DeptCode")
                        .HasColumnType("bigint")
                        .HasColumnName("dept_code");

                    b.Property<long?>("FileCode")
                        .HasColumnType("bigint")
                        .HasColumnName("file_code");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("subject");

                    b.Property<int?>("UserAdded")
                        .HasColumnType("int")
                        .HasColumnName("user_added");

                    b.Property<int?>("UserUpdated")
                        .HasColumnType("int")
                        .HasColumnName("user_updated");

                    b.HasKey("Id");

                    b.ToTable("mails");
                });

            modelBuilder.Entity("Mainfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("AddedBy")
                        .HasColumnType("int")
                        .HasColumnName("added_by");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<bool?>("Archive")
                        .HasColumnType("bit")
                        .HasColumnName("archive");

                    b.Property<string>("Cid")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cid");

                    b.Property<int>("Code")
                        .HasColumnType("int")
                        .HasColumnName("code");

                    b.Property<string>("CompanyEmail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("company_email");

                    b.Property<string>("CompanyFax")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("company_fax");

                    b.Property<string>("CompanyRegister")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("company_register");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_added");

                    b.Property<int?>("ImportJobId")
                        .HasColumnType("int")
                        .HasColumnName("import_job_id");

                    b.Property<string>("Membership")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("membership");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nationality");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note_");

                    b.Property<string>("Partner1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("partner1");

                    b.Property<string>("Partner2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("partner2");

                    b.Property<string>("Partner3")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("partner3");

                    b.Property<string>("RegisterType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("register_type");

                    b.Property<string>("Work")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("work");

                    b.HasKey("Id");

                    b.HasIndex("ImportJobId");

                    b.ToTable("mainfiles");
                });

            modelBuilder.Entity("Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_added");

                    b.Property<long?>("DeptCode")
                        .HasColumnType("bigint")
                        .HasColumnName("dept_code");

                    b.Property<long?>("FileCode")
                        .HasColumnType("bigint")
                        .HasColumnName("file_code");

                    b.Property<string>("NoteText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note_text");

                    b.Property<int?>("UserAdded")
                        .HasColumnType("int")
                        .HasColumnName("user_added");

                    b.Property<int?>("UserUpdated")
                        .HasColumnType("int")
                        .HasColumnName("user_updated");

                    b.HasKey("Id");

                    b.ToTable("notes");
                });

            modelBuilder.Entity("Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdvisorUser")
                        .HasColumnType("int")
                        .HasColumnName("advisor_user");

                    b.Property<string>("AlEntry")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("al_entry");

                    b.Property<int?>("CallcenterUser")
                        .HasColumnType("int")
                        .HasColumnName("callcenter_user");

                    b.Property<bool?>("ClientClosed")
                        .HasColumnType("bit")
                        .HasColumnName("client_closed");

                    b.Property<int?>("Commission")
                        .HasColumnType("int")
                        .HasColumnName("commission");

                    b.Property<bool?>("CommissionClosed")
                        .HasColumnType("bit")
                        .HasColumnName("commission_closed");

                    b.Property<int?>("CourtUser")
                        .HasColumnType("int")
                        .HasColumnName("court_user");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_added");

                    b.Property<long?>("DeptCode")
                        .HasColumnType("bigint")
                        .HasColumnName("dept_code");

                    b.Property<long?>("FileCode")
                        .HasColumnType("bigint")
                        .HasColumnName("file_code");

                    b.Property<string>("FileStatusAfter")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("file_status_after");

                    b.Property<int?>("ImportJobId")
                        .HasColumnType("int")
                        .HasColumnName("import_job_id");

                    b.Property<string>("JouralEntry")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("joural_entry");

                    b.Property<bool?>("JournalClosed")
                        .HasColumnType("bit")
                        .HasColumnName("journal_closed");

                    b.Property<int?>("LawyerUser")
                        .HasColumnType("int")
                        .HasColumnName("lawyer_user");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payment_method");

                    b.Property<string>("SalesAgent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sales_agent");

                    b.Property<string>("SalesCompany")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sales_company");

                    b.Property<DateTime?>("TranslateBackDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("translate_back_date");

                    b.Property<DateTime?>("TranslateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("translate_date");

                    b.Property<int?>("UserAdded")
                        .HasColumnType("int")
                        .HasColumnName("user_added");

                    b.Property<int?>("UserUpdated")
                        .HasColumnType("int")
                        .HasColumnName("user_updated");

                    b.Property<decimal?>("Value")
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("ImportJobId");

                    b.HasIndex("UserAdded");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("PermissionRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminComment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("admin_comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("processed_at");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reason");

                    b.Property<string>("RequestType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("request_type");

                    b.Property<string>("RequestedValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("requested_value");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("permission_requests");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("AccessibleDepartments")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("accessible_departments");

                    b.Property<string>("AccessibleFeatures")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("accessible_features");

                    b.Property<int?>("Code")
                        .HasColumnType("int")
                        .HasColumnName("code");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("department");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("full_name");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2")
                        .HasColumnName("lockout_end");

                    b.Property<string>("PasswordHashed")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PasswordHashed");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PasswordSalt");

                    b.Property<string>("ResetToken")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reset_token");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("datetime2")
                        .HasColumnName("reset_token_expiry");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("role");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("security_stamp");

                    b.Property<string>("SupervisedDepartment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("supervised_department");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("UserBreak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BreakDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("break_date");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("duration_minutes");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_completed");

                    b.Property<int?>("LateMinutes")
                        .HasColumnType("int")
                        .HasColumnName("late_minutes");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_time");

                    b.Property<int?>("UnusedMinutes")
                        .HasColumnType("int")
                        .HasColumnName("unused_minutes");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_breaks");
                });

            modelBuilder.Entity("AutoNumber", b =>
                {
                    b.HasOne("ImportJob", "ImportJob")
                        .WithMany()
                        .HasForeignKey("ImportJobId");

                    b.Navigation("ImportJob");
                });

            modelBuilder.Entity("EmployeeTask", b =>
                {
                    b.HasOne("User", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("FileDetail", b =>
                {
                    b.HasOne("ImportJob", "ImportJob")
                        .WithMany()
                        .HasForeignKey("ImportJobId");

                    b.Navigation("ImportJob");
                });

            modelBuilder.Entity("ImportJob", b =>
                {
                    b.HasOne("User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("LoginHistory", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mainfile", b =>
                {
                    b.HasOne("ImportJob", "ImportJob")
                        .WithMany()
                        .HasForeignKey("ImportJobId");

                    b.Navigation("ImportJob");
                });

            modelBuilder.Entity("Payment", b =>
                {
                    b.HasOne("ImportJob", "ImportJob")
                        .WithMany()
                        .HasForeignKey("ImportJobId");

                    b.HasOne("User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("UserAdded");

                    b.Navigation("CreatedBy");

                    b.Navigation("ImportJob");
                });

            modelBuilder.Entity("PermissionRequest", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserBreak", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
