// <auto-generated />
using System;
using House_of_law_api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace House_of_law_api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260105102500_AddUserBreaksTable")]
    partial class AddUserBreaksTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("House_of_law_api.Domain.Entities.AdditionalAmount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AmountType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("amount_type");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_added");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_updated");

                    b.Property<long?>("DeptCode")
                        .HasColumnType("bigint")
                        .HasColumnName("dept_code");

                    b.Property<bool?>("Enabled")
                        .HasColumnType("bit")
                        .HasColumnName("enabled");

                    b.Property<long?>("FileCode")
                        .HasColumnType("bigint")
                        .HasColumnName("file_code");

                    b.Property<int?>("UserAdded")
                        .HasColumnType("int")
                        .HasColumnName("user_added");

                    b.Property<int?>("UserUpdated")
                        .HasColumnType("int")
                        .HasColumnName("user_updated");

                    b.Property<decimal?>("Value")
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.ToTable("additional_amounts");
                });

            modelBuilder.Entity("House_of_law_api.Domain.Entities.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("attach_code");

                    b.Property<string>("AttachType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("attach_type");

                    b.Property<string>("AutoNumberCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("auto_number_code");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_added");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_updated");

                    b.Property<long?>("DeptCode")
                        .HasColumnType("bigint")
                        .HasColumnName("dept_code");

                    b.Property<bool?>("Enabled")
                        .HasColumnType("bit")
                        .HasColumnName("enabled");

                    b.Property<long?>("FileCode")
                        .HasColumnType("bigint")
                        .HasColumnName("file_code");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<int?>("UserAdded")
                        .HasColumnType("int")
                        .HasColumnName("user_added");

                    b.Property<int?>("UserUpdated")
                        .HasColumnType("int")
                        .HasColumnName("user_updated");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.ToTable("attachments");
                });

            modelBuilder.Entity("House_of_law_api.Domain.Entities.AuditsFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Audit")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("audit");

                    b.Property<long?>("DeptCode")
                        .HasColumnType("bigint")
                        .HasColumnName("dept_code");

                    b.Property<long?>("FileCode")
                        .HasColumnType("bigint")
                        .HasColumnName("file_code");

                    b.Property<int?>("UserAdded")
                        .HasColumnType("int")
                        .HasColumnName("user_added");

                    b.Property<int?>("UserUpdated")
                        .HasColumnType("int")
                        .HasColumnName("user_updated");

                    b.HasKey("Id");

                    b.ToTable("audits_files");
                });

            modelBuilder.Entity("House_of_law_api.Domain.Entities.AutoNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AutoNumberValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("auto_number");

                    b.Property<string>("CaseRef")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("case_ref");

                    b.Property<string>("Claimant")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("claimant");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_added");

                    b.Property<long?>("FileCode")
                        .HasColumnType("bigint")
                        .HasColumnName("file_code");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<int?>("ParentAutoId")
                        .HasColumnType("int")
                        .HasColumnName("parent_auto_id");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.Property<int?>("UserAdded")
                        .HasColumnType("int")
                        .HasColumnName("user_added");

                    b.HasKey("Id");

                    b.ToTable("auto_numbers");
                });

            modelBuilder.Entity("House_of_law_api.Domain.Entities.CallcenterStatement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConnectedStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("connected_status");

                    b.Property<string>("ContactMethod")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contact_method");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_added");

                    b.Property<long?>("DeptCode")
                        .HasColumnType("bigint")
                        .HasColumnName("dept_code");

                    b.Property<long?>("FileCode")
                        .HasColumnType("bigint")
                        .HasColumnName("file_code");

                    b.Property<string>("NextAction")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("next_action");

                    b.Property<DateTime?>("NextDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("next_date");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone_number");

                    b.Property<string>("PhoneOwner")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone_owner");

                    b.Property<decimal?>("PromiseAmount")
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("promise_amount");

                    b.Property<int?>("UserAdded")
                        .HasColumnType("int")
                        .HasColumnName("user_added");

                    b.HasKey("Id");

                    b.ToTable("callcenter_statements");
                });

            modelBuilder.Entity("House_of_law_api.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Code")
                        .HasColumnType("int")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("departments");
                });

            modelBuilder.Entity("House_of_law_api.Domain.Entities.FileClassification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Classification")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("classification");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("code");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_added");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("department");

                    b.Property<long?>("DeptCode")
                        .HasColumnType("bigint")
                        .HasColumnName("dept_code");

                    b.Property<long?>("FileCode")
                        .HasColumnType("bigint")
                        .HasColumnName("file_code");

                    b.Property<int?>("UserAdded")
                        .HasColumnType("int")
                        .HasColumnName("user_added");

                    b.HasKey("Id");

                    b.ToTable("file_classifications");
                });

            modelBuilder.Entity("House_of_law_api.Domain.Entities.FileDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("CanReceiveAutomatedMessages")
                        .HasColumnType("bit")
                        .HasColumnName("can_receive_automated_messages");

                    b.Property<bool?>("CanViewAttachments")
                        .HasColumnType("bit")
                        .HasColumnName("can_view_attachments");

                    b.Property<bool?>("CanViewFinancialMatrix")
                        .HasColumnType("bit")
                        .HasColumnName("can_view_financial_matrix");

                    b.Property<bool?>("CanViewInvoices")
                        .HasColumnType("bit")
                        .HasColumnName("can_view_invoices");

                    b.Property<string>("Client")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("client");

                    b.Property<string>("ContractNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contract_no");

                    b.Property<int?>("CourtEmployee")
                        .HasColumnType("int")
                        .HasColumnName("court_employee");

                    b.Property<int?>("CourtUser")
                        .HasColumnType("int")
                        .HasColumnName("court_user");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_added");

                    b.Property<DateTime?>("DateFinished")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_finished");

                    b.Property<decimal?>("DeptAmount")
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("dept_amount");

                    b.Property<long?>("DeptCode")
                        .HasColumnType("bigint")
                        .HasColumnName("dept_code");

                    b.Property<long?>("FileCode")
                        .HasColumnType("bigint")
                        .HasColumnName("file_code");

                    b.Property<int?>("LawyerUser")
                        .HasColumnType("int")
                        .HasColumnName("lawyer_user");

                    b.Property<int?>("LegalAdvisorUser")
                        .HasColumnType("int")
                        .HasColumnName("legal_advisor_user");

                    b.Property<string>("LegalPlaintiff")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("legal_plaintiff");

                    b.Property<int?>("MdUser")
                        .HasColumnType("int")
                        .HasColumnName("md_user");

                    b.Property<string>("PatchNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("patch_no");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reason");

                    b.HasKey("Id");

                    b.ToTable("file_details");
                });

            modelBuilder.Entity("House_of_law_api.Domain.Entities.FileStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_added");

                    b.Property<int?>("DeptCode")
                        .HasColumnType("int")
                        .HasColumnName("dept_code");

                    b.Property<long?>("FileCode")
                        .HasColumnType("bigint")
                        .HasColumnName("file_code");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("file_statuses");
                });

            modelBuilder.Entity("House_of_law_api.Domain.Entities.Mail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("body");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_added");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_updated");

                    b.Property<long?>("DeptCode")
                        .HasColumnType("bigint")
                        .HasColumnName("dept_code");

                    b.Property<long?>("FileCode")
                        .HasColumnType("bigint")
                        .HasColumnName("file_code");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("subject");

                    b.Property<int?>("UserAdded")
                        .HasColumnType("int")
                        .HasColumnName("user_added");

                    b.Property<int?>("UserUpdated")
                        .HasColumnType("int")
                        .HasColumnName("user_updated");

                    b.HasKey("Id");

                    b.ToTable("mails");
                });

            modelBuilder.Entity("House_of_law_api.Domain.Entities.Mainfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<bool?>("Archive")
                        .HasColumnType("bit")
                        .HasColumnName("archive");

                    b.Property<string>("Cid")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cid");

                    b.Property<int>("Code")
                        .HasColumnType("int")
                        .HasColumnName("code");

                    b.Property<string>("CompanyEmail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("company_email");

                    b.Property<string>("CompanyFax")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("company_fax");

                    b.Property<string>("CompanyRegister")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("company_register");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_added");

                    b.Property<int?>("KafalaAddedBy")
                        .HasColumnType("int")
                        .HasColumnName("kafala_added_by");

                    b.Property<string>("Membership")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("membership");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nationality");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note_");

                    b.Property<string>("Partner1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("partner1");

                    b.Property<string>("Partner2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("partner2");

                    b.Property<string>("Partner3")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("partner3");

                    b.Property<string>("RegisterType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("register_type");

                    b.Property<string>("Work")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("work");

                    b.HasKey("Id");

                    b.ToTable("mainfiles");
                });

            modelBuilder.Entity("House_of_law_api.Domain.Entities.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_added");

                    b.Property<long?>("DeptCode")
                        .HasColumnType("bigint")
                        .HasColumnName("dept_code");

                    b.Property<long?>("FileCode")
                        .HasColumnType("bigint")
                        .HasColumnName("file_code");

                    b.Property<string>("NoteText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note_text");

                    b.Property<int?>("UserAdded")
                        .HasColumnType("int")
                        .HasColumnName("user_added");

                    b.Property<int?>("UserUpdated")
                        .HasColumnType("int")
                        .HasColumnName("user_updated");

                    b.HasKey("Id");

                    b.ToTable("notes");
                });

            modelBuilder.Entity("House_of_law_api.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdvisorUser")
                        .HasColumnType("int")
                        .HasColumnName("advisor_user");

                    b.Property<string>("AlEntry")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("al_entry");

                    b.Property<int?>("CallcenterUser")
                        .HasColumnType("int")
                        .HasColumnName("callcenter_user");

                    b.Property<bool?>("ClientClosed")
                        .HasColumnType("bit")
                        .HasColumnName("client_closed");

                    b.Property<int?>("Commission")
                        .HasColumnType("int")
                        .HasColumnName("commission");

                    b.Property<bool?>("CommissionClosed")
                        .HasColumnType("bit")
                        .HasColumnName("commission_closed");

                    b.Property<int?>("CourtUser")
                        .HasColumnType("int")
                        .HasColumnName("court_user");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_added");

                    b.Property<long?>("DeptCode")
                        .HasColumnType("bigint")
                        .HasColumnName("dept_code");

                    b.Property<long?>("FileCode")
                        .HasColumnType("bigint")
                        .HasColumnName("file_code");

                    b.Property<string>("FileStatusAfter")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("file_status_after");

                    b.Property<string>("JouralEntry")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("joural_entry");

                    b.Property<bool?>("JournalClosed")
                        .HasColumnType("bit")
                        .HasColumnName("journal_closed");

                    b.Property<int?>("LawyerUser")
                        .HasColumnType("int")
                        .HasColumnName("lawyer_user");

                    b.Property<DateTime?>("TranslateBackDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("translate_back_date");

                    b.Property<DateTime?>("TranslateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("translate_date");

                    b.Property<int?>("UserAdded")
                        .HasColumnType("int")
                        .HasColumnName("user_added");

                    b.Property<int?>("UserUpdated")
                        .HasColumnType("int")
                        .HasColumnName("user_updated");

                    b.Property<decimal?>("Value")
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("House_of_law_api.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Code")
                        .HasColumnType("int")
                        .HasColumnName("code");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("department");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHashed")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PasswordHashed");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PasswordSalt");

                    b.Property<string>("ResetToken")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reset_token");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("datetime2")
                        .HasColumnName("reset_token_expiry");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("House_of_law_api.Domain.Entities.UserBreak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BreakDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("break_date");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("duration_minutes");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_completed");

                    b.Property<int?>("LateMinutes")
                        .HasColumnType("int")
                        .HasColumnName("late_minutes");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_time");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_breaks");
                });

            modelBuilder.Entity("House_of_law_api.Domain.Entities.UserBreak", b =>
                {
                    b.HasOne("House_of_law_api.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
